// Generated by CoffeeScript 1.12.7
(function() {
  var align, col, colors, helpers, i18n, sloc, stat,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  sloc = require('../sloc');

  i18n = require('../i18n');

  helpers = require('../helpers');

  align = helpers.alignRight;

  col = 20;

  colors = {
    source: "green",
    comment: "cyan",
    empty: "yellow"
  };

  stat = function(data, options) {
    var c, i, k, n, str, x;
    if (data.badFile) {
      return (align(i18n.en.Error, col)) + " :  " + i18n.en.BadFile;
    }
    str = (function() {
      var j, len, ref, results;
      ref = options.keys;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        k = ref[j];
        if (!((x = data.stats[k]) != null)) {
          continue;
        }
        n = ((c = colors[k]) != null) && ((i = String(x)[c]) != null) ? i : x;
        results.push((align(i18n.en[k], col)) + " :  " + n);
      }
      return results;
    })();
    return str.join('\n');
  };

  module.exports = function(data, options, fmtOpts) {
    if (options == null) {
      options = {};
    }
    return JSON.stringify(data.summary, null, (indexOf.call(fmtOpts, 'no-indent') >= 0 ? 0 : 2));
  };

}).call(this);
